// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAeF9oAKcx-ZoBve9i9thppqM7GC8pLyk',
    appId: '1:1006537100260:web:9c50d3c3695fb2bbd015f1',
    messagingSenderId: '1006537100260',
    projectId: 'farmer-ecommerce-58e37',
    authDomain: 'farmer-ecommerce-58e37.firebaseapp.com',
    storageBucket: 'farmer-ecommerce-58e37.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMG2bczQLuH7iZ0WKOzffTIQ6usA8ryrE',
    appId: '1:1006537100260:android:62784cae2843ec95d015f1',
    messagingSenderId: '1006537100260',
    projectId: 'farmer-ecommerce-58e37',
    storageBucket: 'farmer-ecommerce-58e37.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB66thrtpfiAVu7gTAl4C937qDcFCyV-A4',
    appId: '1:1006537100260:ios:aab7c9c74d51a034d015f1',
    messagingSenderId: '1006537100260',
    projectId: 'farmer-ecommerce-58e37',
    storageBucket: 'farmer-ecommerce-58e37.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB66thrtpfiAVu7gTAl4C937qDcFCyV-A4',
    appId: '1:1006537100260:ios:aab7c9c74d51a034d015f1',
    messagingSenderId: '1006537100260',
    projectId: 'farmer-ecommerce-58e37',
    storageBucket: 'farmer-ecommerce-58e37.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAeF9oAKcx-ZoBve9i9thppqM7GC8pLyk',
    appId: '1:1006537100260:web:9c50d3c3695fb2bbd015f1',
    messagingSenderId: '1006537100260',
    projectId: 'farmer-ecommerce-58e37',
    authDomain: 'farmer-ecommerce-58e37.firebaseapp.com',
    storageBucket: 'farmer-ecommerce-58e37.firebasestorage.app',
  );

}